### ISSUE TITLE
Getting this error: Emarsys::BadRequest: HTTP-Code: 400, Emarsys-Code: 1 - No resource requested.

### ISSUE THREAD

**Issue by eugmandel** [Absolventa/emarsys-rb#1]
I verified that the credentials are correct, but am getting this error from Emarsys on every method call. Any ideas?

**Comment by msenosiain** [comment]
Hi, I'm having the same error on every request, for example

contact = Emarsys::Contact.search(3, ['msenosiain@gmail.com'])

Am I doing something wrong?

Thanks

**Comment by dansch** [comment]
@msenosiain I'm sorry to say but we are not using Emarsys anymore. So we cannot say if there is something wrong with the API. Maybe the Emarsys support can to help you?

**Comment by msenosiain** [comment]
The problema was with the API url ending with a /. Removing it solved the
problem.

**Comment by igl** [comment]
Using query strings i had the problem with the url **not** ending on a `/` 

Fails: `PUT /contact?create_if_not_exists=1`
Works: `PUT /contact/?create_if_not_exists=1`

Don't roll your own url-parsers kids.
