### ISSUE TITLE
Switching to instance-level configuration?

### ISSUE THREAD

**Issue by michaelsauter** [Absolventa/emarsys-rb#28]
Right now the gem is configured via `Emarsys.configure`. That makes it impossible to use with different Emarsys accounts. 

See e.g. http://www.justinweiss.com/articles/3-ways-to-configure-your-ruby-api-wrappers/ for a list of alternatives.

If we would go for an instance, I'd probably re-shuffle quite a bit and have an interface like this: `emarsys_client.contact.create_batch()`.

Thoughts?

**Comment by michaelsauter** [comment]
Any thoughts on this? I fear that we'd have to fork the repo without this. We're going to have 3 Emarsys accounts which we need to talk to from one Rails app.

**Comment by carpodaster** [comment]
👍  Makes sense to allow overriding the global defaults on a per-instance level

**Comment by mungler** [comment]
@michaelsauter yeah, i think it would be best to support the current approach as well as allow overrides, if thats possible? Maintains backward compatibility plus its simpler for the simple case (1 Emarsys account).

**Comment by michaelsauter** [comment]
Good to hear you're open to this.

Could you share how you would keep the current approach while allowing instance-level? Not sure I know what you mean.

About backwards-compatibility, we're currently looking at 3 huge changes, 2 of them definitely breaking:
* Keyword args
* Returning a response instead of the data
* Allowing multiple accounts

Sounds like a major new version to me :)

**Comment by mungler** [comment]
@michaelsauter handily enough, I implemented something *VERY* similar in our Pensio-API gem for the Altapay payment service (formerly Pensio) https://altapay.com

The source is available here: https://github.com/asmallworldsite/pensio_api - note in the documentation the simple case is outlined in the 'Getting Started' section, using something similar to Emarsys:

```PensioAPI::Credentials.base_uri = 'Your pensio gateway URI'
PensioAPI::Credentials.username = 'Your pensio username'
PensioAPI::Credentials.password = 'Your pensio password'```

But there's also the option of multiple named credentials sets, eg:

```
PensioAPI::Credentials.for(:membership).base_uri = 'Your pensio gateway URI for memberships'
PensioAPI::Credentials.for(:membership).username = 'Your pensio username for memberships'
PensioAPI::Credentials.for(:membership).password = 'Your pensio password for memberships'

PensioAPI::Credentials.for(:tickets).base_uri = 'Your pensio gateway URI for tickets'
PensioAPI::Credentials.for(:tickets).username = 'Your pensio username for tickets'
PensioAPI::Credentials.for(:tickets).password = 'Your pensio password for tickets'
```

These are later specified by name in the various method calls, by name (string or symbol) or as an instance.  These three are equivalent:

```PensioAPI::Transaction.find(credentials: :tickets, transaction_id: '123')
PensioAPI::Transaction.find(credentials: 'tickets', transaction_id: '123')
PensioAPI::Transaction.find(credentials: PensioAPI::Credentials.for(:tickets), transaction_id: '123')```

Note that when multiple credentials sets are specified, the code will ignore the default credentials set, and will raise an error if a call is made without specifying one explicitly.  I think this is a sensible pattern to follow for Emarsys.

Here's my original PR for this change in that library - perhaps it might be helpful :) https://github.com/asmallworldsite/pensio_api/pull/4/files

@carpodaster please holler if you disagree with this approach.

**Comment by mungler** [comment]
I guess in the Emarsys case, it could look something like:

```Emarsys.configure do |c|
  c.api_username = EMARSYS_API_USERNAME
  c.api_password = EMARSYS_API_PASSWORD
end
```

in the simple case, and:

```Emarsys.configure(for: :transactional_emails) do |c|
  c.api_username = EMARSYS_API_SYSTEM_EMAILS_ACCOUNT_USERNAME
  c.api_password = EMARSYS_API_SYSTEM_EMAILS_ACCOUNT_PASSWORD
end

Emarsys.configure(for: :marketing_emails) do |c|
  c.api_username = EMARSYS_API_MARKETING_ACCOUNT_USERNAME
  c.api_password = EMARSYS_API_MARKETING_ACCOUNT_PASSWORD
end

Emarsys::Contact.create(account: :marketing_emails, 'user_id', 10, {firstname: "Jane", lastname: "Doe", email: "jane.doe@example.com"})

Emarsys::Email.create({}, account: :marketing_emails)

With an error being raised in the case there are multiple accounts specified and the method call is invoked without specifying an account name.
```

**Comment by michaelsauter** [comment]
@mungler Nice idea, that could work and would allow existing users to keep their code. Let's see what others have to say and then take it from there.

**Comment by michaelsauter** [comment]
I have started to work on multiple accounts, see https://github.com/Absolventa/emarsys-rb/pull/30. It's relatively straightforward, however, we're running into some issues with optional params / keyword arguments.

E.g. we have this call:
```ruby
Emarsys::Contact.export_registrations(distribution_method: 'local', time_range: ["2013-01-01","2013-12-31"], contact_fields: [1,2,3], account: :foo)
```
The method is defined as: 
```ruby
de export_registrations(params = {}, account: nil)
```

Ruby throws:
```
ArgumentError:
  unknown keywords: distribution_method, time_range, contact_fields
```

For more info, read https://makandracards.com/makandra/36011-ruby-do-not-mix-optional-and-keyword-arguments.

So ... my conclusion so far is that we also have to do the transformation to keyword arguments in the same MR if we want to specify the account as a keyword argument :( Not using keyword arguments for the account is pretty bad, too: if it's the first argument then single-account users have to specify `nil` all the time, and if it is the last argument, then multi-account users have to specify all default params.

I started converting the calls to keyword arguments, but I'm a bit unsure what the best way forward is.

I see 2 options atm:

1. All arguments are keyword arguments
E.g. `Emarsys::Contact.update(account: :foo, key_id: 'user_id', key_value: 10, params: {firstname: "Jane", lastname: "Doe", email: "jane.doe@example.com"}, create_if_not_exists: true)`
I like that it is consistent and that it allows to specify the arguments in any order (so one could also move the account bit to the end).

2. Make required params normal arguments, and optional params keyword arguments
E.g. `Emarsys::Contact.update('user_id', 10, {firstname: "Jane", lastname: "Doe", email: "jane.doe@example.com"}, create_if_not_exists: true, account: :foo)`
I like that it is shorter. However it might not always be clear what param should be implemented in which style and it forces the keyword arguments to appear last.

What do you think?

**Comment by michaelsauter** [comment]
@mungler ping

**Comment by mungler** [comment]
@michaelsauter hmm, yeah its a tricky one. Personally i'd bite the bullet and go full kwargs, but I get that its a bigger change. Not sure if @carpodaster has an opinion here, but if not, i'd go for option 1.

**Comment by carpodaster** [comment]
I have only skimmed the comment, sorry. Not really an opinion on this – maybe 55:45 in favor of option no. 1. 

One other thing: what about using double splat instead of `params = {}`?

```ruby
def export_registrations(account: nil, **params)
  # …
end
```

**Comment by michaelsauter** [comment]
@carpodaster Haven't thought of that. I'd say even if that works as expected, we might still run into issues on other methods where we have multiple optional arguments.

**Comment by mungler** [comment]
@carpodaster yeech... not keen on the double splat personally. I think going kwargs is the cleanest approach with the least ambiguity.

**Comment by michaelsauter** [comment]
OK, then I'll convert all arguments to keyword arguments.

**Comment by mungler** [comment]
Closing this issue now that we've merged the relevant PR.
