### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by michaelsauter** [Absolventa/emarsys-rb#40]
I noticed that there are no timeouts set so by default requests time out after 60s. It would be nice to configure this. 

I thought about adding timeout options to the config, and then using the lower-level method  `RestClient::Request.execute(method: method, url: url, open_timeout: open_timeout, read_timeout: read_timeout)`.

Would you be willing to merge this? Then I'll wrap up a PR.

**Comment by mungler** [comment]
Yep
